/**
 * The finishing partner's persistent link, on their Masters card.
 *
 * This replaces the "Partner login" picker that used to sit among the fields.
 * A partner has no account any more — they have this one URL, which always
 * shows whatever work is currently in their hands. Send it once; they bookmark
 * it; nothing expires.
 *
 * THREE STATES, ALL OF THEM REAL:
 *   creating   — the link does not exist yet, because the token is generated by
 *                the row's default. Saying so beats showing an empty box.
 *   no base    — a native build with no EXPO_PUBLIC_APP_BASE_URL cannot know
 *                the app's public origin. Showing the raw token instead of a
 *                half-built URL means nobody sends a link that 404s.
 *   ready      — the link, with Copy (web) / Share (native).
 */
import React, { useState } from 'react';
import { View, Text, StyleSheet } from 'react-native';
import { AppButton } from '../../components/ui/AppButton';
import { buildPartnerLink, portalBaseUrl } from '../../utils/partnerLink';
import { shareOrCopy } from '../../utils/shareLink';
import {
  colors,
  spacing,
  radius,
  fontSize,
  fontWeight,
  fontFamily,
} from '../../constants/theme';

export function PartnerLinkPanel({ token, isNew }: { token: string | null; isNew: boolean }) {
  const [status, setStatus] = useState<string | null>(null);
  const link = buildPartnerLink(token);

  if (isNew || !token) {
    return (
      <View style={styles.panel}>
        <Text style={styles.title}>Partner link</Text>
        <Text style={styles.body}>
          A permanent link is generated when this partner is saved. Reopen the card afterwards to
          copy it — it is how the partner sees the work handed to them, and they never need a
          login.
        </Text>
      </View>
    );
  }

  return (
    <View style={styles.panel}>
      <Text style={styles.title}>Partner link</Text>
      <Text style={styles.body}>
        Send this once. It always shows this partner their current work, with no login. Archiving
        the partner revokes it.
      </Text>

      <View style={styles.linkBox}>
        <Text style={styles.link} selectable numberOfLines={3}>
          {link ?? token}
        </Text>
      </View>

      {!link ? (
        <Text style={styles.warn}>
          Set EXPO_PUBLIC_APP_BASE_URL to build the full URL on this platform. The value above is
          the token only.
        </Text>
      ) : null}

      <View style={styles.actions}>
        <AppButton
          title="Copy / share link"
          variant="secondary"
          size="sm"
          onPress={async () => {
            const outcome = await shareOrCopy(link ?? token, 'Finishing partner link');
            setStatus(
              outcome === 'copied'
                ? 'Copied to clipboard.'
                : outcome === 'shared'
                ? 'Shared.'
                : 'Could not copy — select the link above and copy it manually.'
            );
          }}
        />
        {status ? <Text style={styles.status}>{status}</Text> : null}
      </View>
    </View>
  );
}

const styles = StyleSheet.create({
  panel: {
    marginBottom: spacing.xl,
    padding: spacing.lg,
    borderRadius: radius.md,
    borderWidth: 1,
    borderColor: colors.border,
    backgroundColor: colors.surface,
    gap: spacing.sm,
  },
  title: {
    fontFamily: fontFamily.display,
    fontSize: fontSize.secondary,
    fontWeight: fontWeight.semibold,
    color: colors.ink,
  },
  body: { fontSize: fontSize.caption, color: colors.inkMuted, lineHeight: 18 },
  linkBox: {
    padding: spacing.md,
    borderRadius: radius.sm,
    backgroundColor: colors.bg,
    borderWidth: 1,
    borderColor: colors.border,
  },
  link: { fontFamily: fontFamily.mono, fontSize: fontSize.caption, color: colors.ink },
  warn: { fontSize: fontSize.caption, color: colors.alert, lineHeight: 18 },
  actions: { gap: spacing.xs, alignItems: 'flex-start' },
  status: { fontSize: fontSize.caption, color: colors.inkMuted },
});

export default PartnerLinkPanel;
